// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm9KAX2ZsA-_REEr3wScCIR6Wv-g86TGM',
    appId: '1:812958055889:web:ce12639800bca162e0f4f0',
    messagingSenderId: '812958055889',
    projectId: 'qdfitness-b99b3',
    authDomain: 'qdfitness-b99b3.firebaseapp.com',
    storageBucket: 'qdfitness-b99b3.appspot.com',
    measurementId: 'G-707BL7TM03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIkj5dNNmX-Y7YioSzwF7xPrAa6iJNkc0',
    appId: '1:812958055889:android:3220de044bbc04cae0f4f0',
    messagingSenderId: '812958055889',
    projectId: 'qdfitness-b99b3',
    storageBucket: 'qdfitness-b99b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA0SDonl6Gpjt9u4bA-7s8g5yN4k3DCUw',
    appId: '1:812958055889:ios:df7fae51e851a63be0f4f0',
    messagingSenderId: '812958055889',
    projectId: 'qdfitness-b99b3',
    storageBucket: 'qdfitness-b99b3.appspot.com',
    androidClientId: '812958055889-ckj97m031fajste540v3j735162ov38v.apps.googleusercontent.com',
    iosClientId: '812958055889-uctihngih5lcotm3d0v01k39jtbusjii.apps.googleusercontent.com',
    iosBundleId: 'com.qd.qdfitness',
  );
}
